# Generated by Django 4.0.2 on 2022-09-30 15:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book_issue',
            name='book_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.book'),
        ),
        migrations.AlterField(
            model_name='book_issue',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 8, 20, 39, 53, 629046), help_text='Date the book is due to'),
        ),
        migrations.DeleteModel(
            name='BookInstance',
        ),
    ]
