# Generated by Django 4.0.2 on 2022-09-30 15:57

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_book_available_book_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='address',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='fullname',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='program',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='students',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='students',
            name='Guardian_name',
        ),
        migrations.RemoveField(
            model_name='students',
            name='roll_number',
        ),
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='fine',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='students',
            name='prn',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book_issue',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 8, 21, 27, 4, 755521), help_text='Date the book is due to'),
        ),
    ]
