# Generated by Django 4.0.2 on 2022-09-30 16:17

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_rename_address_students_book_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prn', models.CharField(max_length=100)),
                ('fine', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='book_issue',
            name='book_instance',
        ),
        migrations.RemoveField(
            model_name='book_issue',
            name='remarks_on_issue',
        ),
        migrations.RemoveField(
            model_name='book_issue',
            name='remarks_on_return',
        ),
        migrations.RemoveField(
            model_name='book_issue',
            name='student',
        ),
        migrations.RemoveField(
            model_name='students',
            name='book',
        ),
        migrations.RemoveField(
            model_name='students',
            name='fine',
        ),
        migrations.AddField(
            model_name='book_issue',
            name='book_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_issue',
            name='prn',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book_issue',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 8, 21, 47, 16, 1601), help_text='Date the book is due to'),
        ),
    ]
