# Generated by Django 4.0.2 on 2022-10-01 04:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_alter_book_book_title_alter_book_issue_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='books_issued',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book_issue',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 9, 9, 36, 45, 215651), help_text='Date the book is due to'),
        ),
    ]
