# Generated by Django 4.0.2 on 2022-10-01 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_delete_fine_students_fine_alter_book_issue_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record_Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prn', models.CharField(max_length=100)),
                ('book_title', models.CharField(max_length=200)),
                ('issue_date', models.DateField(blank=True, help_text='Date the book is issued', null=True)),
                ('date_returned', models.DateField(auto_now=True, help_text='Date the book is returned')),
            ],
        ),
        migrations.RemoveField(
            model_name='book_issue',
            name='date_returned',
        ),
        migrations.AlterField(
            model_name='book_issue',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 9, 10, 26, 57, 905982), help_text='Date the book is due to'),
        ),
    ]
