# Generated by Django 4.0.2 on 2022-11-10 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_record_issue_remove_book_issue_date_returned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_issue',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 18, 18, 14, 12, 271873), help_text='Date the book is due to'),
        ),
    ]
